package com.bawei.hujintao.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.hujintao.model.bean.RxxpBean;

import com.bawei.hujintao.database.RxxpBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rxxpBeanDaoConfig;

    private final RxxpBeanDao rxxpBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rxxpBeanDaoConfig = daoConfigMap.get(RxxpBeanDao.class).clone();
        rxxpBeanDaoConfig.initIdentityScope(type);

        rxxpBeanDao = new RxxpBeanDao(rxxpBeanDaoConfig, this);

        registerDao(RxxpBean.class, rxxpBeanDao);
    }
    
    public void clear() {
        rxxpBeanDaoConfig.clearIdentityScope();
    }

    public RxxpBeanDao getRxxpBeanDao() {
        return rxxpBeanDao;
    }

}
